### ISSUE TITLE
Package breaks on ruamel.yaml 0.17.27

### ISSUE THREAD

**Issue by jawsper** [looztra/yamkix#132]
It seems `ruamel.yaml.comments.NoComment` was renamed to `NotNone`. The changed happened in this commit: https://sourceforge.net/p/ruamel-yaml/code/ci/ea1ad6788f7880621043be18251afab8368e64da/

This then breaks yamkix when it's imported in `comments.py`.

**Comment by looztra** [comment]
Do you need a version compatible with ruamel.yaml <= 0.17.26?

Or do we go only with a fix compatible with ruamel.yaml >= 0.17.27?

What do you think @jawsper ?

**Comment by looztra** [comment]
version 0.10.0 has been published to pypi, it enforces ruamel.yaml >= 0.17.27

**Comment by jawsper** [comment]
Awesome, thanks for the quick fix!
